//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winformAdminLibrarySystem.LibraryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="publishers", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class publishers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.books[] booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_publisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_publisherField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.books[] books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_publisher {
            get {
                return this.id_publisherField;
            }
            set {
                if ((this.id_publisherField.Equals(value) != true)) {
                    this.id_publisherField = value;
                    this.RaisePropertyChanged("id_publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_publisher {
            get {
                return this.name_publisherField;
            }
            set {
                if ((object.ReferenceEquals(this.name_publisherField, value) != true)) {
                    this.name_publisherField = value;
                    this.RaisePropertyChanged("name_publisher");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="books", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aboutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.authors_books[] authors_booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.download[] downloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.genres_books[] genres_booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_publisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int imprint_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.publishers publishersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string about {
            get {
                return this.aboutField;
            }
            set {
                if ((object.ReferenceEquals(this.aboutField, value) != true)) {
                    this.aboutField = value;
                    this.RaisePropertyChanged("about");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.authors_books[] authors_books {
            get {
                return this.authors_booksField;
            }
            set {
                if ((object.ReferenceEquals(this.authors_booksField, value) != true)) {
                    this.authors_booksField = value;
                    this.RaisePropertyChanged("authors_books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.download[] download {
            get {
                return this.downloadField;
            }
            set {
                if ((object.ReferenceEquals(this.downloadField, value) != true)) {
                    this.downloadField = value;
                    this.RaisePropertyChanged("download");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.genres_books[] genres_books {
            get {
                return this.genres_booksField;
            }
            set {
                if ((object.ReferenceEquals(this.genres_booksField, value) != true)) {
                    this.genres_booksField = value;
                    this.RaisePropertyChanged("genres_books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_book {
            get {
                return this.id_bookField;
            }
            set {
                if ((this.id_bookField.Equals(value) != true)) {
                    this.id_bookField = value;
                    this.RaisePropertyChanged("id_book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_publisher {
            get {
                return this.id_publisherField;
            }
            set {
                if ((this.id_publisherField.Equals(value) != true)) {
                    this.id_publisherField = value;
                    this.RaisePropertyChanged("id_publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int imprint_date {
            get {
                return this.imprint_dateField;
            }
            set {
                if ((this.imprint_dateField.Equals(value) != true)) {
                    this.imprint_dateField = value;
                    this.RaisePropertyChanged("imprint_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_book {
            get {
                return this.name_bookField;
            }
            set {
                if ((object.ReferenceEquals(this.name_bookField, value) != true)) {
                    this.name_bookField = value;
                    this.RaisePropertyChanged("name_book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pages {
            get {
                return this.pagesField;
            }
            set {
                if ((this.pagesField.Equals(value) != true)) {
                    this.pagesField = value;
                    this.RaisePropertyChanged("pages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.publishers publishers {
            get {
                return this.publishersField;
            }
            set {
                if ((object.ReferenceEquals(this.publishersField, value) != true)) {
                    this.publishersField = value;
                    this.RaisePropertyChanged("publishers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="authors_books", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class authors_books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.authors authorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.books booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_bookField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.authors authors {
            get {
                return this.authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.authorsField, value) != true)) {
                    this.authorsField = value;
                    this.RaisePropertyChanged("authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.books books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_author {
            get {
                return this.id_authorField;
            }
            set {
                if ((this.id_authorField.Equals(value) != true)) {
                    this.id_authorField = value;
                    this.RaisePropertyChanged("id_author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_book {
            get {
                return this.id_bookField;
            }
            set {
                if ((this.id_bookField.Equals(value) != true)) {
                    this.id_bookField = value;
                    this.RaisePropertyChanged("id_book");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="download", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class download : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.books booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_downloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.users usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.books books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_book {
            get {
                return this.id_bookField;
            }
            set {
                if ((this.id_bookField.Equals(value) != true)) {
                    this.id_bookField = value;
                    this.RaisePropertyChanged("id_book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_download {
            get {
                return this.id_downloadField;
            }
            set {
                if ((this.id_downloadField.Equals(value) != true)) {
                    this.id_downloadField = value;
                    this.RaisePropertyChanged("id_download");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.users users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="genres_books", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class genres_books : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.books booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.genres genresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_bookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_genreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.books books {
            get {
                return this.booksField;
            }
            set {
                if ((object.ReferenceEquals(this.booksField, value) != true)) {
                    this.booksField = value;
                    this.RaisePropertyChanged("books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.genres genres {
            get {
                return this.genresField;
            }
            set {
                if ((object.ReferenceEquals(this.genresField, value) != true)) {
                    this.genresField = value;
                    this.RaisePropertyChanged("genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_book {
            get {
                return this.id_bookField;
            }
            set {
                if ((this.id_bookField.Equals(value) != true)) {
                    this.id_bookField = value;
                    this.RaisePropertyChanged("id_book");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_genre {
            get {
                return this.id_genreField;
            }
            set {
                if ((this.id_genreField.Equals(value) != true)) {
                    this.id_genreField = value;
                    this.RaisePropertyChanged("id_genre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="authors", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class authors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.authors_books[] authors_booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_authorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string patronymicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string year_of_birthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string year_of_deathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.authors_books[] authors_books {
            get {
                return this.authors_booksField;
            }
            set {
                if ((object.ReferenceEquals(this.authors_booksField, value) != true)) {
                    this.authors_booksField = value;
                    this.RaisePropertyChanged("authors_books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_author {
            get {
                return this.id_authorField;
            }
            set {
                if ((this.id_authorField.Equals(value) != true)) {
                    this.id_authorField = value;
                    this.RaisePropertyChanged("id_author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string patronymic {
            get {
                return this.patronymicField;
            }
            set {
                if ((object.ReferenceEquals(this.patronymicField, value) != true)) {
                    this.patronymicField = value;
                    this.RaisePropertyChanged("patronymic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year_of_birth {
            get {
                return this.year_of_birthField;
            }
            set {
                if ((object.ReferenceEquals(this.year_of_birthField, value) != true)) {
                    this.year_of_birthField = value;
                    this.RaisePropertyChanged("year_of_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string year_of_death {
            get {
                return this.year_of_deathField;
            }
            set {
                if ((object.ReferenceEquals(this.year_of_deathField, value) != true)) {
                    this.year_of_deathField = value;
                    this.RaisePropertyChanged("year_of_death");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="users", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.download[] downloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.download[] download {
            get {
                return this.downloadField;
            }
            set {
                if ((object.ReferenceEquals(this.downloadField, value) != true)) {
                    this.downloadField = value;
                    this.RaisePropertyChanged("download");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="genres", Namespace="http://schemas.datacontract.org/2004/07/MyConsoleApplication.Model")]
    [System.SerializableAttribute()]
    public partial class genres : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private winformAdminLibrarySystem.LibraryService.genres_books[] genres_booksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_genreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_genreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public winformAdminLibrarySystem.LibraryService.genres_books[] genres_books {
            get {
                return this.genres_booksField;
            }
            set {
                if ((object.ReferenceEquals(this.genres_booksField, value) != true)) {
                    this.genres_booksField = value;
                    this.RaisePropertyChanged("genres_books");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_genre {
            get {
                return this.id_genreField;
            }
            set {
                if ((this.id_genreField.Equals(value) != true)) {
                    this.id_genreField = value;
                    this.RaisePropertyChanged("id_genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_genre {
            get {
                return this.name_genreField;
            }
            set {
                if ((object.ReferenceEquals(this.name_genreField, value) != true)) {
                    this.name_genreField = value;
                    this.RaisePropertyChanged("name_genre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryService.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllPublisher", ReplyAction="http://tempuri.org/IMyService/GetAllPublisherResponse")]
        winformAdminLibrarySystem.LibraryService.publishers[] GetAllPublisher();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllPublisher", ReplyAction="http://tempuri.org/IMyService/GetAllPublisherResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.publishers[]> GetAllPublisherAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdPublisher", ReplyAction="http://tempuri.org/IMyService/GetByIdPublisherResponse")]
        winformAdminLibrarySystem.LibraryService.publishers GetByIdPublisher(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdPublisher", ReplyAction="http://tempuri.org/IMyService/GetByIdPublisherResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.publishers> GetByIdPublisherAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddPublisher", ReplyAction="http://tempuri.org/IMyService/AddPublisherResponse")]
        void AddPublisher(winformAdminLibrarySystem.LibraryService.publishers publisher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddPublisher", ReplyAction="http://tempuri.org/IMyService/AddPublisherResponse")]
        System.Threading.Tasks.Task AddPublisherAsync(winformAdminLibrarySystem.LibraryService.publishers publisher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdatePublisher", ReplyAction="http://tempuri.org/IMyService/UpdatePublisherResponse")]
        void UpdatePublisher(winformAdminLibrarySystem.LibraryService.publishers publisher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdatePublisher", ReplyAction="http://tempuri.org/IMyService/UpdatePublisherResponse")]
        System.Threading.Tasks.Task UpdatePublisherAsync(winformAdminLibrarySystem.LibraryService.publishers publisher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeletePublisher", ReplyAction="http://tempuri.org/IMyService/DeletePublisherResponse")]
        void DeletePublisher(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeletePublisher", ReplyAction="http://tempuri.org/IMyService/DeletePublisherResponse")]
        System.Threading.Tasks.Task DeletePublisherAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchPublisher", ReplyAction="http://tempuri.org/IMyService/SearchPublisherResponse")]
        winformAdminLibrarySystem.LibraryService.publishers[] SearchPublisher(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchPublisher", ReplyAction="http://tempuri.org/IMyService/SearchPublisherResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.publishers[]> SearchPublisherAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllAuthor", ReplyAction="http://tempuri.org/IMyService/GetAllAuthorResponse")]
        winformAdminLibrarySystem.LibraryService.authors[] GetAllAuthor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllAuthor", ReplyAction="http://tempuri.org/IMyService/GetAllAuthorResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.authors[]> GetAllAuthorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdAuthor", ReplyAction="http://tempuri.org/IMyService/GetByIdAuthorResponse")]
        winformAdminLibrarySystem.LibraryService.authors GetByIdAuthor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdAuthor", ReplyAction="http://tempuri.org/IMyService/GetByIdAuthorResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.authors> GetByIdAuthorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddAuthor", ReplyAction="http://tempuri.org/IMyService/AddAuthorResponse")]
        void AddAuthor(winformAdminLibrarySystem.LibraryService.authors author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddAuthor", ReplyAction="http://tempuri.org/IMyService/AddAuthorResponse")]
        System.Threading.Tasks.Task AddAuthorAsync(winformAdminLibrarySystem.LibraryService.authors author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateAuthor", ReplyAction="http://tempuri.org/IMyService/UpdateAuthorResponse")]
        void UpdateAuthor(winformAdminLibrarySystem.LibraryService.authors author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateAuthor", ReplyAction="http://tempuri.org/IMyService/UpdateAuthorResponse")]
        System.Threading.Tasks.Task UpdateAuthorAsync(winformAdminLibrarySystem.LibraryService.authors author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteAuthor", ReplyAction="http://tempuri.org/IMyService/DeleteAuthorResponse")]
        void DeleteAuthor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteAuthor", ReplyAction="http://tempuri.org/IMyService/DeleteAuthorResponse")]
        System.Threading.Tasks.Task DeleteAuthorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchAuthor", ReplyAction="http://tempuri.org/IMyService/SearchAuthorResponse")]
        winformAdminLibrarySystem.LibraryService.authors[] SearchAuthor(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchAuthor", ReplyAction="http://tempuri.org/IMyService/SearchAuthorResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.authors[]> SearchAuthorAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllGenre", ReplyAction="http://tempuri.org/IMyService/GetAllGenreResponse")]
        winformAdminLibrarySystem.LibraryService.genres[] GetAllGenre();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllGenre", ReplyAction="http://tempuri.org/IMyService/GetAllGenreResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.genres[]> GetAllGenreAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdGenre", ReplyAction="http://tempuri.org/IMyService/GetByIdGenreResponse")]
        winformAdminLibrarySystem.LibraryService.genres GetByIdGenre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdGenre", ReplyAction="http://tempuri.org/IMyService/GetByIdGenreResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.genres> GetByIdGenreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddGenre", ReplyAction="http://tempuri.org/IMyService/AddGenreResponse")]
        void AddGenre(winformAdminLibrarySystem.LibraryService.genres genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddGenre", ReplyAction="http://tempuri.org/IMyService/AddGenreResponse")]
        System.Threading.Tasks.Task AddGenreAsync(winformAdminLibrarySystem.LibraryService.genres genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateGenre", ReplyAction="http://tempuri.org/IMyService/UpdateGenreResponse")]
        void UpdateGenre(winformAdminLibrarySystem.LibraryService.genres genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateGenre", ReplyAction="http://tempuri.org/IMyService/UpdateGenreResponse")]
        System.Threading.Tasks.Task UpdateGenreAsync(winformAdminLibrarySystem.LibraryService.genres genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteGenre", ReplyAction="http://tempuri.org/IMyService/DeleteGenreResponse")]
        void DeleteGenre(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteGenre", ReplyAction="http://tempuri.org/IMyService/DeleteGenreResponse")]
        System.Threading.Tasks.Task DeleteGenreAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchGenre", ReplyAction="http://tempuri.org/IMyService/SearchGenreResponse")]
        winformAdminLibrarySystem.LibraryService.genres[] SearchGenre(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchGenre", ReplyAction="http://tempuri.org/IMyService/SearchGenreResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.genres[]> SearchGenreAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllBook", ReplyAction="http://tempuri.org/IMyService/GetAllBookResponse")]
        string[] GetAllBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllBook", ReplyAction="http://tempuri.org/IMyService/GetAllBookResponse")]
        System.Threading.Tasks.Task<string[]> GetAllBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdBook", ReplyAction="http://tempuri.org/IMyService/GetByIdBookResponse")]
        winformAdminLibrarySystem.LibraryService.books GetByIdBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetByIdBook", ReplyAction="http://tempuri.org/IMyService/GetByIdBookResponse")]
        System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.books> GetByIdBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddBook", ReplyAction="http://tempuri.org/IMyService/AddBookResponse")]
        void AddBook(winformAdminLibrarySystem.LibraryService.books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddBook", ReplyAction="http://tempuri.org/IMyService/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(winformAdminLibrarySystem.LibraryService.books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateBook", ReplyAction="http://tempuri.org/IMyService/UpdateBookResponse")]
        void UpdateBook(winformAdminLibrarySystem.LibraryService.books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateBook", ReplyAction="http://tempuri.org/IMyService/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(winformAdminLibrarySystem.LibraryService.books book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteBook", ReplyAction="http://tempuri.org/IMyService/DeleteBookResponse")]
        void DeleteBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteBook", ReplyAction="http://tempuri.org/IMyService/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchBook", ReplyAction="http://tempuri.org/IMyService/SearchBookResponse")]
        string[] SearchBook(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/SearchBook", ReplyAction="http://tempuri.org/IMyService/SearchBookResponse")]
        System.Threading.Tasks.Task<string[]> SearchBookAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetLastIdBook", ReplyAction="http://tempuri.org/IMyService/GetLastIdBookResponse")]
        int GetLastIdBook();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetLastIdBook", ReplyAction="http://tempuri.org/IMyService/GetLastIdBookResponse")]
        System.Threading.Tasks.Task<int> GetLastIdBookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddAB", ReplyAction="http://tempuri.org/IMyService/AddABResponse")]
        void AddAB(winformAdminLibrarySystem.LibraryService.authors_books ab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddAB", ReplyAction="http://tempuri.org/IMyService/AddABResponse")]
        System.Threading.Tasks.Task AddABAsync(winformAdminLibrarySystem.LibraryService.authors_books ab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateAB", ReplyAction="http://tempuri.org/IMyService/UpdateABResponse")]
        void UpdateAB(winformAdminLibrarySystem.LibraryService.authors_books ab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateAB", ReplyAction="http://tempuri.org/IMyService/UpdateABResponse")]
        System.Threading.Tasks.Task UpdateABAsync(winformAdminLibrarySystem.LibraryService.authors_books ab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteABId", ReplyAction="http://tempuri.org/IMyService/DeleteABIdResponse")]
        void DeleteABId(int l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteABId", ReplyAction="http://tempuri.org/IMyService/DeleteABIdResponse")]
        System.Threading.Tasks.Task DeleteABIdAsync(int l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddGB", ReplyAction="http://tempuri.org/IMyService/AddGBResponse")]
        void AddGB(winformAdminLibrarySystem.LibraryService.genres_books gb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddGB", ReplyAction="http://tempuri.org/IMyService/AddGBResponse")]
        System.Threading.Tasks.Task AddGBAsync(winformAdminLibrarySystem.LibraryService.genres_books gb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateGB", ReplyAction="http://tempuri.org/IMyService/UpdateGBResponse")]
        void UpdateGB(winformAdminLibrarySystem.LibraryService.genres_books gb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateGB", ReplyAction="http://tempuri.org/IMyService/UpdateGBResponse")]
        System.Threading.Tasks.Task UpdateGBAsync(winformAdminLibrarySystem.LibraryService.genres_books gb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteGBId", ReplyAction="http://tempuri.org/IMyService/DeleteGBIdResponse")]
        void DeleteGBId(int l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteGBId", ReplyAction="http://tempuri.org/IMyService/DeleteGBIdResponse")]
        System.Threading.Tasks.Task DeleteGBIdAsync(int l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : winformAdminLibrarySystem.LibraryService.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<winformAdminLibrarySystem.LibraryService.IMyService>, winformAdminLibrarySystem.LibraryService.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public winformAdminLibrarySystem.LibraryService.publishers[] GetAllPublisher() {
            return base.Channel.GetAllPublisher();
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.publishers[]> GetAllPublisherAsync() {
            return base.Channel.GetAllPublisherAsync();
        }
        
        public winformAdminLibrarySystem.LibraryService.publishers GetByIdPublisher(int id) {
            return base.Channel.GetByIdPublisher(id);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.publishers> GetByIdPublisherAsync(int id) {
            return base.Channel.GetByIdPublisherAsync(id);
        }
        
        public void AddPublisher(winformAdminLibrarySystem.LibraryService.publishers publisher) {
            base.Channel.AddPublisher(publisher);
        }
        
        public System.Threading.Tasks.Task AddPublisherAsync(winformAdminLibrarySystem.LibraryService.publishers publisher) {
            return base.Channel.AddPublisherAsync(publisher);
        }
        
        public void UpdatePublisher(winformAdminLibrarySystem.LibraryService.publishers publisher) {
            base.Channel.UpdatePublisher(publisher);
        }
        
        public System.Threading.Tasks.Task UpdatePublisherAsync(winformAdminLibrarySystem.LibraryService.publishers publisher) {
            return base.Channel.UpdatePublisherAsync(publisher);
        }
        
        public void DeletePublisher(int id) {
            base.Channel.DeletePublisher(id);
        }
        
        public System.Threading.Tasks.Task DeletePublisherAsync(int id) {
            return base.Channel.DeletePublisherAsync(id);
        }
        
        public winformAdminLibrarySystem.LibraryService.publishers[] SearchPublisher(string str) {
            return base.Channel.SearchPublisher(str);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.publishers[]> SearchPublisherAsync(string str) {
            return base.Channel.SearchPublisherAsync(str);
        }
        
        public winformAdminLibrarySystem.LibraryService.authors[] GetAllAuthor() {
            return base.Channel.GetAllAuthor();
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.authors[]> GetAllAuthorAsync() {
            return base.Channel.GetAllAuthorAsync();
        }
        
        public winformAdminLibrarySystem.LibraryService.authors GetByIdAuthor(int id) {
            return base.Channel.GetByIdAuthor(id);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.authors> GetByIdAuthorAsync(int id) {
            return base.Channel.GetByIdAuthorAsync(id);
        }
        
        public void AddAuthor(winformAdminLibrarySystem.LibraryService.authors author) {
            base.Channel.AddAuthor(author);
        }
        
        public System.Threading.Tasks.Task AddAuthorAsync(winformAdminLibrarySystem.LibraryService.authors author) {
            return base.Channel.AddAuthorAsync(author);
        }
        
        public void UpdateAuthor(winformAdminLibrarySystem.LibraryService.authors author) {
            base.Channel.UpdateAuthor(author);
        }
        
        public System.Threading.Tasks.Task UpdateAuthorAsync(winformAdminLibrarySystem.LibraryService.authors author) {
            return base.Channel.UpdateAuthorAsync(author);
        }
        
        public void DeleteAuthor(int id) {
            base.Channel.DeleteAuthor(id);
        }
        
        public System.Threading.Tasks.Task DeleteAuthorAsync(int id) {
            return base.Channel.DeleteAuthorAsync(id);
        }
        
        public winformAdminLibrarySystem.LibraryService.authors[] SearchAuthor(string str) {
            return base.Channel.SearchAuthor(str);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.authors[]> SearchAuthorAsync(string str) {
            return base.Channel.SearchAuthorAsync(str);
        }
        
        public winformAdminLibrarySystem.LibraryService.genres[] GetAllGenre() {
            return base.Channel.GetAllGenre();
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.genres[]> GetAllGenreAsync() {
            return base.Channel.GetAllGenreAsync();
        }
        
        public winformAdminLibrarySystem.LibraryService.genres GetByIdGenre(int id) {
            return base.Channel.GetByIdGenre(id);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.genres> GetByIdGenreAsync(int id) {
            return base.Channel.GetByIdGenreAsync(id);
        }
        
        public void AddGenre(winformAdminLibrarySystem.LibraryService.genres genre) {
            base.Channel.AddGenre(genre);
        }
        
        public System.Threading.Tasks.Task AddGenreAsync(winformAdminLibrarySystem.LibraryService.genres genre) {
            return base.Channel.AddGenreAsync(genre);
        }
        
        public void UpdateGenre(winformAdminLibrarySystem.LibraryService.genres genre) {
            base.Channel.UpdateGenre(genre);
        }
        
        public System.Threading.Tasks.Task UpdateGenreAsync(winformAdminLibrarySystem.LibraryService.genres genre) {
            return base.Channel.UpdateGenreAsync(genre);
        }
        
        public void DeleteGenre(int id) {
            base.Channel.DeleteGenre(id);
        }
        
        public System.Threading.Tasks.Task DeleteGenreAsync(int id) {
            return base.Channel.DeleteGenreAsync(id);
        }
        
        public winformAdminLibrarySystem.LibraryService.genres[] SearchGenre(string str) {
            return base.Channel.SearchGenre(str);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.genres[]> SearchGenreAsync(string str) {
            return base.Channel.SearchGenreAsync(str);
        }
        
        public string[] GetAllBook() {
            return base.Channel.GetAllBook();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllBookAsync() {
            return base.Channel.GetAllBookAsync();
        }
        
        public winformAdminLibrarySystem.LibraryService.books GetByIdBook(int id) {
            return base.Channel.GetByIdBook(id);
        }
        
        public System.Threading.Tasks.Task<winformAdminLibrarySystem.LibraryService.books> GetByIdBookAsync(int id) {
            return base.Channel.GetByIdBookAsync(id);
        }
        
        public void AddBook(winformAdminLibrarySystem.LibraryService.books book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(winformAdminLibrarySystem.LibraryService.books book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public void UpdateBook(winformAdminLibrarySystem.LibraryService.books book) {
            base.Channel.UpdateBook(book);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(winformAdminLibrarySystem.LibraryService.books book) {
            return base.Channel.UpdateBookAsync(book);
        }
        
        public void DeleteBook(int id) {
            base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(int id) {
            return base.Channel.DeleteBookAsync(id);
        }
        
        public string[] SearchBook(string str) {
            return base.Channel.SearchBook(str);
        }
        
        public System.Threading.Tasks.Task<string[]> SearchBookAsync(string str) {
            return base.Channel.SearchBookAsync(str);
        }
        
        public int GetLastIdBook() {
            return base.Channel.GetLastIdBook();
        }
        
        public System.Threading.Tasks.Task<int> GetLastIdBookAsync() {
            return base.Channel.GetLastIdBookAsync();
        }
        
        public void AddAB(winformAdminLibrarySystem.LibraryService.authors_books ab) {
            base.Channel.AddAB(ab);
        }
        
        public System.Threading.Tasks.Task AddABAsync(winformAdminLibrarySystem.LibraryService.authors_books ab) {
            return base.Channel.AddABAsync(ab);
        }
        
        public void UpdateAB(winformAdminLibrarySystem.LibraryService.authors_books ab) {
            base.Channel.UpdateAB(ab);
        }
        
        public System.Threading.Tasks.Task UpdateABAsync(winformAdminLibrarySystem.LibraryService.authors_books ab) {
            return base.Channel.UpdateABAsync(ab);
        }
        
        public void DeleteABId(int l) {
            base.Channel.DeleteABId(l);
        }
        
        public System.Threading.Tasks.Task DeleteABIdAsync(int l) {
            return base.Channel.DeleteABIdAsync(l);
        }
        
        public void AddGB(winformAdminLibrarySystem.LibraryService.genres_books gb) {
            base.Channel.AddGB(gb);
        }
        
        public System.Threading.Tasks.Task AddGBAsync(winformAdminLibrarySystem.LibraryService.genres_books gb) {
            return base.Channel.AddGBAsync(gb);
        }
        
        public void UpdateGB(winformAdminLibrarySystem.LibraryService.genres_books gb) {
            base.Channel.UpdateGB(gb);
        }
        
        public System.Threading.Tasks.Task UpdateGBAsync(winformAdminLibrarySystem.LibraryService.genres_books gb) {
            return base.Channel.UpdateGBAsync(gb);
        }
        
        public void DeleteGBId(int l) {
            base.Channel.DeleteGBId(l);
        }
        
        public System.Threading.Tasks.Task DeleteGBIdAsync(int l) {
            return base.Channel.DeleteGBIdAsync(l);
        }
    }
}
