//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class authors
    {
        public authors()
        {
            this.authors_books = new HashSet<authors_books>();
        }
    
        [DataMember]
        public int id_author { get; set; }

        [DataMember]
        public string surname { get; set; }

        [DataMember]
        public string name { get; set; }

        [DataMember]
        public string patronymic { get; set; }

        [DataMember]
        public string year_of_birth { get; set; }

        [DataMember]
        public string year_of_death { get; set; }

        [DataMember]
        public virtual ICollection<authors_books> authors_books { get; set; }
    }
}
