//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]    
    public partial class books
    {
        public books()
        {
            this.authors_books = new HashSet<authors_books>();
            this.download = new HashSet<download>();
            this.genres_books = new HashSet<genres_books>();
        }

        [DataMember]
        public int id_book { get; set; }

        [DataMember]
        public string name_book { get; set; }

        [DataMember]
        public int id_publisher { get; set; }

        [DataMember]
        public int imprint_date { get; set; }

        [DataMember]
        public int pages { get; set; }

        [DataMember]
        public string about { get; set; }

        [DataMember]
        public string text { get; set; }

        [DataMember]
        public string image { get; set; }

        [DataMember]
        public virtual ICollection<authors_books> authors_books { get; set; }

        [DataMember]
        public virtual publishers publishers { get; set; }

        [DataMember]
        public virtual ICollection<download> download { get; set; }

        [DataMember]
        public virtual ICollection<genres_books> genres_books { get; set; }
    }
}
