//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]    
    public partial class genres
    {
        public genres()
        {
            this.genres_books = new HashSet<genres_books>();
        }

        [DataMember]
        public int id_genre { get; set; }

        [DataMember]
        public string name_genre { get; set; }

        [DataMember]
        public virtual ICollection<genres_books> genres_books { get; set; }
    }
}
