//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]    
    public partial class genres_books
    {
        [DataMember]
        public int id { get; set; }

        [DataMember]
        public int id_genre { get; set; }

        [DataMember]
        public int id_book { get; set; }

        [DataMember]
        public virtual books books { get; set; }

        [DataMember]
        public virtual genres genres { get; set; }
    }
}
