//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryEntities : DbContext
    {
        public libraryEntities()
            : base("name=libraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<authors> authors { get; set; }
        public DbSet<authors_books> authors_books { get; set; }
        public DbSet<books> books { get; set; }
        public DbSet<download> download { get; set; }
        public DbSet<genres> genres { get; set; }
        public DbSet<genres_books> genres_books { get; set; }
        public DbSet<publishers> publishers { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<users> users { get; set; }
    }
}
