//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]    
    public partial class publishers
    {
        public publishers()
        {
            this.books = new HashSet<books>();
        }
    
        [DataMember]
        public int id_publisher { get; set; }

        [DataMember]
        public string name_publisher { get; set; }

        [DataMember]
        public virtual ICollection<books> books { get; set; }
    }
}
