//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConsoleApplication.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]    
    public partial class users
    {
        public users()
        {
            this.download = new HashSet<download>();
        }
    
        [DataMember]
        public int id_user { get; set; }

        [DataMember]
        public string login { get; set; }

        [DataMember]
        public string password { get; set; }

        [DataMember]
        public string email { get; set; }

        [DataMember]
        public virtual ICollection<download> download { get; set; }
    }
}
